workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods
          pod install
      - name: Build iOS
        script: |
          xcodebuild -workspace YourApp.xcworkspace -scheme YourScheme -sdk iphoneos -configuration Release archive -archivePath $HOME/output/MyApp.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $HOME/output/MyApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $HOME/output
    artifacts:
      - $HOME/output/MyApp.ipa
