workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      cocoapods: default
      app_store_connect_apple_id: $APP_STORE_CONNECT_APPLE_ID
      app_store_connect_team_id: $APP_STORE_CONNECT_TEAM_ID
      app_store_connect_key_id: $APP_STORE_CONNECT_KEY_ID
      app_store_connect_issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      app_store_connect_private_key: $APP_STORE_CONNECT_PRIVATE_KEY
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods
          pod install
      - name: Build iOS
        script: |
          xcodebuild -workspace YourApp.xcworkspace -scheme YourScheme -sdk iphoneos -configuration Release archive -archivePath $HOME/output/MyApp.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $HOME/output/MyApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $HOME/output
    artifacts:
      - $HOME/output/MyApp.ipa
